#!/usr/bin/env python
# ~/.python27rc
# This is a startup script for python

print 'GREETINGS, welcome to python.'
import matplotlib.pyplot as plt
import numpy as np

# Plot Sthg cool everytime
x=np.linspace(-2,2,1000)
y1=np.sqrt(1-(abs(x)-1)**2)
y2=-2*np.sqrt(1-(abs(x)/2)**0.5)
plt.ion() #Allow interactive plot session
plt.fill_between(x,y1,color='red')
plt.fill_between(x,y2,color='red')
plt.text(0, -0.4, time.asctime(), \
fontsize=24, fontweight='bold', color='white', horizontalalignment='center')
plt.show()
time.sleep(1)
plt.close('all')

